### ISSUE TITLE
Doesn't build -- implicit dependency on Fiveam?

### ISSUE THREAD

**Issue by xach** [alpha123/cl-template#1]
I can't load this without manually loading Fiveam first. It looks like cl-template-tests and cl-template share packages.lisp? Since that file references Fiveam that means the main cl-template system must also depend-on fiveam.

**Comment by alpha123** [comment]
Ah yes, I forgot about that - thank you. I'll fix this as soon as I return to my development computer.

Do you recommend splitting it into two packages.lisp so cl-template can be loaded independently (I assume most users aren't going to want to run the tests), add fiveam to the cl-template dependencies, or something else? (Sorry, this is the first CL library I've publicly distributed.)
